name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run apt update
      run: |
        sudo apt update
        sudo apt upgrade
    - name: Run LaTeX install
      run: |
        sudo apt install -y texlive-lang-cjk xdvik-ja evince
        sudo apt install -y texlive-fonts-recommended texlive-fonts-extra
